### ISSUE TITLE
The override tab `chrome_url_overrides` browser is not defined

### ISSUE THREAD

**Issue by tonyyang924** [mozilla/webextension-polyfill#174] opened 2019-01-29 07:59 UTC
The running script has been included by HTML. Although I already included `browser-polyfill.min.js` that it still doesn't work.

It always show up error message: browser is not defined

```html
<html>
<head>
    <script type="text/javascript" src="./browser-ployfill.min.js"></script>
    <script type="text/javascript" src="./newtab.js"></script>
</head>
<body>
</body>
</html>
```

```js
window.onload = () => {
    browser.tabs.xxxxx
};
```

**Comment by rpl** [comment] 2019-01-29 13:22
@tonyyang924 we need some additional details to make this issue actually actionable, it may be useful if you could attach a small test extension that reproduce the issue with the minimum amount of code and assets, and the steps to reproduce the issue (and also on which browser you are able to reproduce the issue, e.g. [if the issue can only be reproduced on Firefox then it is not a webextension-polyfill issue, because this polyfill acts as a no-op on Firefox](https://github.com/mozilla/webextension-polyfill#issues-that-happen-only-when-running-on-firefox)).

**Comment by tophf** [comment] 2019-02-02 17:44
`ployfill` in the script's src should be `polyfill`.

**Comment by rpl** [comment] 2019-02-03 09:57
@tophf good catch! the typo is very likely the reason for the issue.

@tonyyang924 I'm closing this as invalid, feel free to re-open if the typo wasn't the reason for the issue you experienced locally (and you can provide the additional details needed to investigate it).

**Closed by rpl** 2019-02-03 09:57 UTC
Labels: state: invalid

**Comment by tonyyang924** [comment] 2019-02-04 06:05
@tophf  lol, that was my mistake,  typo error, I fixed it and it works! thx a lot
@rpl It is the reason for typo XD
