### ISSUE TITLE
Different way of checking if browser is defined?

### ISSUE THREAD

**Issue by fstanis** [mozilla/webextension-polyfill#68] opened 2017-10-15 22:40 UTC
I found a peculiar bug with using webextension-polyfill in webpack: [issue 5828](https://github.com/webpack/webpack/issues/5828).

Long story short, the polyfill guard confuses webpack in certain circumstances:
https://github.com/mozilla/webextension-polyfill/blob/8914541b8135b2e154762b01c26ee16f5a064954/src/browser-polyfill.js#L9

This got me thinking, any reason why something simpler like `if (!window.browser) {` is not used here instead?

**Comment by rpl** [comment] 2017-10-16 20:56
@fstanis That's really unfortunate :-(

but also: Thanks you for letting us know!

we are going to evaluate if we should workaround it in the polyfill itself.

**Comment by JannesMeyer** [comment] 2018-04-15 11:02
Hi,

I just came across the same problem, and it seems that the problem has been fixed. However the last release on npm was 6 months ago, which doesn't include the fix yet. Any idea when the next release will happen?

Thanks

**Comment by ExE-Boss** [comment] 2018-05-12 09:44
I personally prefer using:
```js
if (!("browser" in window)) {
    // [...]
}
```

**Comment by tophf** [comment] 2018-07-21 10:13
Currently this polyfill can be trivially disabled by adding a DOM element with id `browser` in the page - in case the polyfill runs as a content script when that element is already in the page, that is at the default state of `"run_at"`. 

This is possible because browsers create implicit global variables for such elements and of course their type is not `undefined`, it's `object`. I guess you can add a check for `instanceof Node`.

See https://crbug.com/865881

**Comment by varjolintu** [comment] 2018-07-21 12:44
@tophf Thanks for linking the bug here. I was just about to make a new issue. It's a really annoying problem. At first I feared that you could extend the element prototype and override the browser.runtime for some nasty code but luckily that didn't work.

Many pages can have an element ID'd as `browser` and this indeed breaks the content script every time.

**Comment by rpl** [comment] 2018-08-16 13:38
#153 fixed the issue mention in https://github.com/mozilla/webextension-polyfill/issues/68#issuecomment-406785652, #3 already cover the Edge use case and @Rob--W filed #156 for the remaining issue with webpack.ProvidePlugin.

I'm closing this as a duplicate of #156.

**Closed by rpl** 2018-08-16 13:38 UTC
Labels: component: polyfill wrappers, priority: enhancement, type: discussion

**Comment by fregante** [comment] 2022-03-29 04:38
Note: version 0.9.0 supports `ProvidePlugin` now thanks to #351 

```js
plugins: [
  new ProvidePlugin({
    browser: "webextension-polyfill"
  })
]
```
