### ISSUE TITLE
How to use mv3 background service workers? 

### ISSUE THREAD

**Issue by z0ccc** [mozilla/webextension-polyfill#374] opened 2022-03-25 18:07 UTC
Hi,

The in mv2 background scripts are declared like this:

```
  "background": {
    "scripts": [
      "browser-polyfill.js",
      "background.js"
    ]
  },
```

But mv3 only allows a single service worker like this: 

```
  "background": {
    "service_worker": "background.js"
  },
```

How would use both "browser-polyfill.js" and "background.js" as service workers in mv3?

Thanks

**Comment by Insiro** [comment] 2022-03-26 16:37
in top of background.js
insert 
`importScripts("path/to/polyfill/browser-polyfill.min.js");`

**Comment by Rob--W** [comment] 2022-03-31 13:59
Duplicate of https://github.com/mozilla/webextension-polyfill/issues/363. We should indeed document how `importScripts` can be used.

> but declarativeNetRequest not support yet...

What do you mean by that? Even if DNR is not in the polyfill source, the polyfill will just forward the API access requests to the underlying APIs.

**Closed by Rob--W** 2022-03-31 13:59 UTC

**Comment by Insiro** [comment] 2022-03-31 14:46
it just means I waiting for DNR support
I have a plan to use Dynamic to replace blocking on webRequest.onBeforeRequest
you mean.. there's another way to do like this??
