### ISSUE TITLE
Using in a Unit Testing environment

### ISSUE THREAD

**Issue by davestewart** [mozilla/webextension-polyfill#236] opened 2020-08-29 19:51 UTC
Not sure if this is the right place to ask, but when attempting to use in Jest tests, I get the following error:

```
This script should only be loaded in a browser extension
```

I was attempting to use in conjunction with `sinon-chrome` to mock the Browser API and begin to test my extension, but I can't seem to get the `chrome` object in the right context for the polyfill to work:

https://github.com/acvetkov/sinon-chrome/issues/103

I'm a "fair weather" tester, so I will be the first to admit I may have no idea what I'm doing and perhaps should not be tackling things this way.

Can anyone advise?

Thank you.

**Comment by nickmccurdy** [comment] 2020-08-30 00:24
This fixed it for me https://github.com/mozilla/webextension-polyfill/issues/218#issuecomment-584936358

**Comment by Rob--W** [comment] 2020-09-01 16:46
Duplicate of #218. Thanks nick for linking https://github.com/mozilla/webextension-polyfill/issues/218#issuecomment-584936358

**Closed by Rob--W** 2020-09-01 16:46 UTC

**Comment by davestewart** [comment] 2020-09-01 17:32
Thanks @nickmccurdy and @Rob--W!

Not sure why I didn't search the issues.

Not sure if you consider it in-scope to perhaps add a section (even links) to the home page?

It's really the next logical step for anything you expect to be used my more than a few people.

Thanks again 👍

**Comment by Rob--W** [comment] 2020-09-01 17:47
I think that the best way to solve this bug is to set a non-void extension ID in `chrome.runtime.id` in the sinon-chrome library (or at least document it there). This "problem" is not specific to this polyfill, but generally to any consumer of sinon-chrome.

**Comment by nickmccurdy** [comment] 2020-09-01 19:02
Should we suggest a fix upstream? It seems like a common issue, I'm not sure why it's initialized to `null`.

**Comment by Rob--W** [comment] 2020-09-01 19:54
It wouldn't hurt to ask. sinon-chrome's primary responsibility seems to be the generation of stubs, and it's up to the consumers of that library to provide meaningful implementations. In this case, a value for `chrome.runtime.id`.
