### ISSUE TITLE
Uncaught (in promise) errors missing stacktrace

### ISSUE THREAD

**Issue by franciscolourenco** [mozilla/webextension-polyfill#224] opened 2020-03-18 14:14 UTC
Couldn't we reject `new Error(extensionAPIs.runtime.lastError.message)` to get a stacktrace?

https://github.com/mozilla/webextension-polyfill/blob/c77e9fb89d82898afdcadf2e6740099e3c93b1bf/src/browser-polyfill.js#L91-L94

**Comment by Rob--W** [comment] 2020-03-18 21:55
> Couldn't we reject `new Error(extensionAPIs.runtime.lastError.message)` to get a stacktrace?

No. `chrome.runtime.lastError` does normally not even contain a stack trace.

Anyway, this is a duplicate of #210.

**Closed** 2020-03-18 21:55 UTC
Labels: state: duplicate
