### ISSUE TITLE
RuntimeMessage: message reply cannot be cloned

### ISSUE THREAD

**Issue by davidb1** [mozilla/webextension-polyfill#235] opened 2020-08-05 10:09 UTC
After latest Firefox 79.0 update started getting this error from sendMessage

Code:
```
import browser from "webextension-polyfill";

export const background_script_api = new Proxy(
  {},
  {
    get(target, command) {
      return (data) => browser.runtime.sendMessage({ command, data })
    },
  }
);
```

Throws:
```
Error: Conduits:RuntimeMessage: message reply cannot be cloned.
 get background-communicator.js:7
```

**Comment by rpl** [comment] 2020-08-05 11:14
@davidb1 The webextension-polyfill does not have anything to do with that error, when running on Firefox the polyfill turns itself into a no-op ([see  the related section of the README file in this repo](https://github.com/mozilla/webextension-polyfill#issues-that-happen-only-when-running-on-firefox)), and so I'm going to close this issue as invalid for this repo.

The issue is very likely triggered by the extension itself by trying to reply to a message with an object that can't be send across the processes, and so it is expected to fail in that case, but the error message isn't supposed to expose the "Conduits::RuntimeMessage" part because it is an internal implementation detail, and so it may be worth reporting it on bugzilla (possibly by also attaching a minimal test extension that reproduce the issue and the steps to reproduce it consistently), a link to a partially pre-filled form to file the bug is available in the section of the readme linked above.

**Closed by rpl** 2020-08-05 11:14 UTC
Labels: state: invalid

**Comment by rpl** [comment] 2020-08-05 14:52
@davidb1 I filed the issue on bugzilla as [Bug 1657384 - runtime messaging API does throw "Error: Conduits:RuntimeMessage: message reply cannot be cloned."](https://bugzilla.mozilla.org/show_bug.cgi?id=1657384).

Would you mind to add to that issue a link to the extension that does already trigger the issue and the steps to reproduce it consistently? 
(or even here on this issue, or send it to me by email, I'll take care of updating the issue with those additional details)

The additional details will help us to look for investigate the issue further and identify the exact patch that introduced the change in behavior.

Thanks in advance!

**Comment by AnityTranslator** [comment] 2020-08-05 20:19
Hi @rpl, We are also experiencing issues with exactly this bug on our extension.

The extension is [Anity](https://addons.mozilla.org/en-US/firefox/addon/anity/)

Steps to reproduce:

1. Firefox browser version 79.0
2. go to japanese comics image: [example image](https://image.rawdevart.com/comic/tensei-kizoku-no-isekai-boukenroku-jichou-wo-shiranai-kamigami-no-shito/chapters/24/005.jpg)
3. Click the Anity extension -> Click translate

Expected:
Loading bar should appear at the end of which the text on the image should be translated to English

Actual:
Loading bar appears but the text is not translated (due to client error from bug)

We have also validated that this does not happen on different browsers and does not happen on versions 78.0 and lower.

Thank you very much

**Comment by Rob--W** [comment] 2020-08-06 23:19
@AnityTranslator I cannot reproduce the issue with version 2.0.2 of your extension, only 2.0.1. What did you change and why?

**Comment by AnityTranslator** [comment] 2020-08-07 12:18
@Rob--W The following API's were not working as expected following the Firefox 79 update:
- `browser.runtime.sendMessage();` and `browser.tabs.sendMessage();` aren't able to serialize messages to JSON that were previously serializable. 
   Some examples:
   1. `undefined` now throws the aforementioned `message reply cannot be cloned`. 
   2. axios responses that were previously serializable now throw a similar message.
- `browser.runtime.sendMessage();` and `browser.tabs.sendMessage();` - couldn't await on a response from them, even when the message was serializable. (I didn't dig too deep and made a temporary fix for 79 - passing and receiving messages one way)

**Comment by Rob--W** [comment] 2020-08-14 14:44
> @Rob--W The following API's were not working as expected following the Firefox 79 update:
> 
>     * `browser.runtime.sendMessage();` and `browser.tabs.sendMessage();` aren't able to serialize messages to JSON that were previously serializable.
>       Some examples:
>       
>       1. `undefined` now throws the aforementioned `message reply cannot be cloned`.

I cannot reproduce. Sending `undefined` (whether from sendMessage or in onMessage) works for me.

>       2. axios responses that were previously serializable now throw a similar message.

I guess that you returned `axios.get()` or something like that? The object has a `request` member which is an instance of `XMLHttpRequest`. That object is not serializable. Previously, the value would be replaced with an empty plain object, but as of 79 that is no longer the case. I saw that you patched your code by (de)serializing as JSON. This works but it's just patchwork - the real fix is to only return values in which you're interested.

>     * `browser.runtime.sendMessage();` and `browser.tabs.sendMessage();` - couldn't await on a response from them, even when the message was serializable. (I didn't dig too deep and made a temporary fix for 79 - passing and receiving messages one way)

I cannot reproduce this with one onMessage listener and a sendMessage call. Can you provide a bit more detail on how this issue can be reproduced?
