### ISSUE TITLE
Compatibility with environments that have the `browser` namespace but don't support promises

### ISSUE THREAD

**Issue by snoack** [mozilla/webextension-polyfill#3] opened 2016-10-21 13:59 UTC
This polyfill seems to be incompatible with Microsoft Edge, which doesn't support promises yet, but is using the `browser` instead of the `chrome` namespace.

**Comment by kmaglione** [comment] 2016-11-06 22:46
Edge is planning to add promise support, but yes, I've been thinking about ways to detect this and add support where it's not available.

**Comment by snoack** [comment] 2016-11-09 14:21
Well, I presume it will still take a while until Microsoft Edge will support promises, and when it does extension developers might not be able to drop support for older versions of Microsoft Edge right away. Also what if Chrome (or a new platform) will start to provide the `browser` namespace but doesn't support promises in the same step.

As for detecting the promise-based API, the best idea I have is just calling any asynchronous function and check whether it throws an exception (because a callback is expected) or whether a promise is returned.

```js
if (typeof browser == "undefined")
  var browser = chrome;

var _supportsPromises = false;
try {
  _supportsPromises = browser.runtime.getPlatformInfo() instanceof Promise;
}
catch (e)
{
}

if (!_supportsPromises)
  browser = wrapAPI(browser);
```

**Comment by DaAwesomeP** [comment] 2017-04-16 03:03
Here's the issue on the Microsoft end: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9421085/. Maybe they'll post an update if a decent amount of people click the "Me too" button.

**Comment by myfreeweb** [comment] 2017-04-22 10:57
'Changed Status from “Confirmed” to “By design”' :(

**Comment by DaAwesomeP** [comment] 2017-04-26 15:17
>  James M. Apr 24, 2017 Microsoft Edge Team
> 
> Hello,
> 
> Thank you for providing this information about the issue. A Microsoft Edge Extension does not support the Promise model; this is a documented difference between Mozilla and Edge’s platform. Currently, we do not plan to release a fix. Please update this case if you can provide new information for us to consider.
> 
> Best Wishes,
> The MS Edge Team

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9421085/

**Comment by myfreeweb** [comment] 2017-04-30 14:53
Considering Microsoft's track record of not following standards and their somewhat recent desire to not be like that anymore, it's really weird that they're so dismissive about this…

I guess supporting this in the polyfill would be the only solution for now :(

**Comment by Noitidart** [comment] 2017-04-30 18:48
Ideally I would like to use this polyfill but due to edge I was using this really short polyfill and it was working well:

```
const deepAccessUsingString = (obj, dotpath) => dotpath.split('.').reduce((nested, key) => nested[key], obj);

const TRUNK = window.chrome && window.chrome.runtime ? window.chrome : window.browser;

window.extension = TRUNK;
window.extensiona = function(dotpath, ...args) {
    let basepath = dotpath.split('.');
    basepath.pop();
    basepath = basepath.join('.');
    return new Promise(resolve => deepAccessUsingString(TRUNK, dotpath)(...args, resolve));
};
```

The only issue i see is in `extensiona` (the promise version), using `deepAccessUsingString` might disconnect the api call from the the `this`. I haven't had issues with it yet though.

**Comment by bfred-it** [comment] 2017-08-20 11:47
It looks like Chrome doesn't care about Mozilla's WebExtensions effort and Edge is just Chrome's pet.

**Comment by myfreeweb** [comment] 2017-08-20 14:05
@bfred-it uhh this repo is exactly the polyfill :)

**Comment by bfred-it** [comment] 2017-08-20 15:14
Yeah but mozilla's API still looks like `browser.runtime.onBrowserUpdateAvailable.addListener()`, which is so bad it's almost funny.

It should have been a more "standard" `browser.runtime.on('BrowserUpdateAvailable', fn)`

**Comment by myfreeweb** [comment] 2017-08-20 23:42
that's pretty minor compared to using promises instead of callbacks

**Comment by osdiab** [comment] 2017-08-22 10:05
Aw man, just began working on a Web Extension and ran into this. Hope this can be prioritized soon / maybe I'll try to take a jab at it at some point.

**Comment by myfreeweb** [comment] 2017-08-22 12:03
@osdiab look at #43 which was mentioned here

**Comment by constfun** [comment] 2017-10-10 01:17
At the moment, neither a working polyfill, nor any other cross browser solution exists.
An unfortunate state of affairs, but we people of the web are used to this by now. 

May I suggest some possible improvements: 
1. Address idiosyncrasies of each browser vendor explicitly, based on the user agent, instead of [the current approach](https://github.com/mozilla/webextension-polyfill/blob/61d92ea79bcd7ecce8396a6827fa02e8631cde61/src/browser-polyfill.js#L9).
2. Instead of polyfilling globals, export an object with Mozilla's version of the API. 

On point 1, I argue that it is more robust and simpler than attempting non-trivial feature detection, as in #43. The set of browsers currently supporting WebExtensions is known and the chances of your extension working in some other incarnation of the API without being explicitly targeted is slim. 

On point 2, an anecdote. 

I just had a fun time on a project that also uses [pastak/chrome-browser-object-polyfill](https://github.com/pastak/chrome-browser-object-polyfill). That polyfill makes its own assumptions about the `browser` global. [MetaMask/extensionizer](https://github.com/MetaMask/extensionizer) makes  different assumptions still.

A cross platform library is more useful to me as a developer than a polyfill that seals off all escape hatches by monkey patching globals.

Thoughts?

**Comment by Noitidart** [comment] 2017-10-10 02:25
@constfun I find this works for me across all browsers including edge:

```
const deepAccessUsingString = (obj, dotpath) => dotpath.split('.').reduce((nested, key) => nested[key], obj);

window.extension = typeof chrome !== 'undefined' && chrome.runtime ? chrome : browser;
window.extensiona = function(dotpath, ...args) {
    let basepath = dotpath.split('.');
    basepath.pop();
    basepath = basepath.join('.');
    return new Promise(resolve => deepAccessUsingString(TRUNK, dotpath)(...args, resolve));
}


/* USAGE - sync apis */
extension.browserAction.onClicked.addListener(handleClick);
extension.tabs.create({ url:'blah' }); // if dont care about return
extension.browserAction.setTitle({ title:'rawr' })

/* USAGE - async/callback based api's are as promise */
async function() {
    const info = await extensiona('runtime.getPlatformInfo');
    const tabInfo = await extensiona('tabs.create', { url:'blah' });
    const download = await extensiona('downloads.download', { filename:`filename.here`, url:`www.bing.com/blah` });
}
```

**Comment by franklinyu** [comment] 2018-01-08 03:47
The Edge issue has been re-opened by Edge team…

**Comment by Rob--W** [comment] 2018-05-31 13:29
@rpl and I talked about this:

- We want to support Edge, with minimal efforts (i.e. no large changes).
- That is, a simple feature detection as shown in https://github.com/mozilla/webextension-polyfill/issues/3#issuecomment-259425339 (guarded on the existence of the Edge-specific `msBrowser` API).
- The (existing) `browser` object will be replaced with the polyfilled one, which uses the global `chrome` object to implement the polyfill.
- The polyfill should be tested (at least manually, ideally with continuous integration).

**Comment by NN---** [comment] 2018-06-17 17:20
@Rob--W Any estimations for including this functionality in webextension-polyfill ?

**Comment by Rob--W** [comment] 2018-08-20 15:57
One of the big blockers is the ability to load an extension in Edge for automated testing (locally and on continuous integration, e.g. on AppVeyor).

If someone spends time on researching that, then I am willing to make the desired changes to the polyfill to support Edge.

**Comment by mjethani** [comment] 2018-09-22 14:46
In Adblock Plus we have written our own [polyfill](https://github.com/adblockplus/adblockpluschrome/blob/57d2b171b7f00206d9e05c56222bd4d303ccc65f/polyfill.js#L66) to wrap the async APIs on Chrome and Edge. It works for us.

**Comment by dessant** [comment] 2018-09-22 15:12
@Rob--W. the lack of automated testing isn't necessarily a blocker for releasing this feature.

**Comment by franklinyu** [comment] 2018-09-22 19:56
@Rob--W Sadly AppVeyor won’t support Microsoft Edge testing. All tests on AppVeyor run on [Windows Server 2012/2016](https://www.appveyor.com/docs/windows-images-software/#operating-system), but MS Edge [doesn’t support Windows Server at all](https://superuser.com/questions/1247448/how-to-install-microsoft-edge-on-windows-server-2016). So far the only option that I know is [BrowserStack](https://www.browserstack.com/list-of-browsers-and-platforms?product=automate), which [has free plan for open-source projects](https://www.browserstack.com/open-source), but I guess it would take some time to set up Selenium.

I think we Edge users would be happy enough if Edge is supported on a best-effort basis. We don’t need any guarantee about non-breaking release because we understand the difficulty.

**Comment by tophf** [comment] 2018-12-11 18:09
Soon [Edge will use Chromium inside](https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/) so it's reasonable to expect Edge will have the classic chrome API for extensions, which would solve the polyfill compatibility problem too.

**Comment by NN---** [comment] 2018-12-11 18:52
There are many companies using Edge right now.
It will take time for MS to release a Chromium based version and more time for companies to upgrade.

**Comment by FranklinYu** [comment] 2018-12-11 19:08
TBH Microsoft announced that too early. Now nobody would develop against the classic MS Edge no matter when the new Edge come out. This is not the only project; there is also some discussion at EFForg/https-everywhere#5101.

**Comment by NN---** [comment] 2018-12-11 19:55
Unfortunately, I do have to develop for current Edge.:(

**Comment by rpl** [comment] 2019-01-07 12:51
Closing as wontfix. See https://github.com/mozilla/webextension-polyfill/pull/114#issuecomment-451923835 for a rationale.

@NN--- @vozeldr you may give a try to the alternative approach described in the above comment (and in the [example-msedge-extension-with-webextension-polyfill](https://github.com/rpl/example-msedge-extension-with-webextension-polyfill) github repo).

**Closed by rpl** 2019-01-07 12:51 UTC
Labels: platform: edge, priority: enhancement, state: wontfix

**Comment by NN---** [comment] 2019-01-07 13:58
I already do the same using Webpack and currently don't need any Edge specific features.
Just added window.chrome=window.browser prior running any extension code.
Anyway thanks for the sample, maybe I find it useful in the future.
